# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
url: "http://fxzjshm.github.io" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Fxzjshm's place # on Github 
  #avatar: avatar.png
  hometitle: Home #display on navigation menu.
  yoursitetitle: #YOUR LOGO
  gravatar: # Email MD5 hash
  description: #"used by search engines" # used by search engines
  visiblewords: 100
  # Header and footer text
  header_text: #
    #Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   # <p style="color:white"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">fxzjshm.github.io</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://fxzjshm.github.io/" property="cc:attributionName" rel="cc:attributionURL">fxzjshm</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p> 

  # Icons
  rss: false
  email_address: "fxzjshm@163.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "fxzjshm"
  flickr:
  github: "fxzjshm"
  weibo: "fxzjshm"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "fxzjshm"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "-->" #"Next"
  str_prev: "<--" #"Prev"
  str_continue_reading: "..." #"Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: #"fengzhichu.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/ 

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate
